In [6]:
import numpy as np

In [2]:
#indixes where value is 4:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("\n orginal array",arr)
x=np.where(arr==4)
print(x)


 orginal array [1 2 3 4 5 6 7 8 9]
(array([3], dtype=int64),)


In [3]:
#indexes where the values are even :
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [10]:
import numpy as np
# sorting
arr=np.array([3,2,0,1])
k=np.sort(arr)
print(k)

[0 1 2 3]


In [16]:
#filter 
arr=np.array([22,33,44,55])
filter_arr=arr>44
p=arr[filter_arr]
print(p)

[55]


In [19]:
a=np.array([[2,5,4,1,0],[9,7,8,3,11]])
l=np.sort(a)
print(l)

[[ 0  1  2  4  5]
 [ 3  7  8  9 11]]
