In [1]:
import numpy as np

In [5]:
a=np.array([10,20,30,40,50])
b=np.array([11,22,33,44,55])

In [6]:
#vector addition 
print(a+b)

[ 21  42  63  84 105]


In [7]:
#vector subtraction 
print(a-b)

[-1 -2 -3 -4 -5]


In [8]:
#vector multiplication
print(a*b)

[ 110  440  990 1760 2750]


In [10]:
#vector dot product
print(a.dot(b))

6050


In [11]:
#vector divison
print(a/b)

[0.90909091 0.90909091 0.90909091 0.90909091 0.90909091]


In [12]:
#scalar multiplication 
scr=4
print(a*scr)

[ 40  80 120 160 200]


In [15]:
#vectorize
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
arr1=[10,4,20]
arr2=[2,3,30]
vec_func=np.vectorize(my_func)
print(vec_func(arr1,arr2))


[ 8  1 50]
