In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
b=np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


In [10]:
c=np.zeros((2,2))
print(c)

[[0. 0.]
 [0. 0.]]


In [11]:
d=np.full((3,4),4)
print(d)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [12]:
e=np.random.random((3,3))
print(e)

[[0.65614471 0.9430195  0.45212383]
 [0.70205419 0.21959894 0.41389157]
 [0.32549376 0.89539192 0.19060261]]


In [13]:
f=np.arange(2,99,0.5)
print(f)

[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5
 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5
 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5
 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5 36.  36.5
 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5 43.  43.5
 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5 49.  49.5 50.  50.5
 51.  51.5 52.  52.5 53.  53.5 54.  54.5 55.  55.5 56.  56.5 57.  57.5
 58.  58.5 59.  59.5 60.  60.5 61.  61.5 62.  62.5 63.  63.5 64.  64.5
 65.  65.5 66.  66.5 67.  67.5 68.  68.5 69.  69.5 70.  70.5 71.  71.5
 72.  72.5 73.  73.5 74.  74.5 75.  75.5 76.  76.5 77.  77.5 78.  78.5
 79.  79.5 80.  80.5 81.  81.5 82.  82.5 83.  83.5 84.  84.5 85.  85.5
 86.  86.5 87.  87.5 88.  88.5 89.  89.5 90.  90.5 91.  91.5 92.  92.5
 93.  93.5 94.  94.5 95.  95.5 96.  96.5 97.  97.5 98.  98.5]


In [16]:
h=d.reshape((2,6))
print(h)

[[4 4 4 4 4 4]
 [4 4 4 4 4 4]]


In [18]:
k=d.flatten()
print(k)

[4 4 4 4 4 4 4 4 4 4 4 4]


In [19]:
print(f.shape)

(194,)


In [20]:
len(f)

194

In [21]:
print(f.dtype)

float64


In [24]:
print(f.astype('int'))

[ 2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10 10 11 11 12 12 13 13
 14 14 15 15 16 16 17 17 18 18 19 19 20 20 21 21 22 22 23 23 24 24 25 25
 26 26 27 27 28 28 29 29 30 30 31 31 32 32 33 33 34 34 35 35 36 36 37 37
 38 38 39 39 40 40 41 41 42 42 43 43 44 44 45 45 46 46 47 47 48 48 49 49
 50 50 51 51 52 52 53 53 54 54 55 55 56 56 57 57 58 58 59 59 60 60 61 61
 62 62 63 63 64 64 65 65 66 66 67 67 68 68 69 69 70 70 71 71 72 72 73 73
 74 74 75 75 76 76 77 77 78 78 79 79 80 80 81 81 82 82 83 83 84 84 85 85
 86 86 87 87 88 88 89 89 90 90 91 91 92 92 93 93 94 94 95 95 96 96 97 97
 98 98]


In [25]:
f[0:150]

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5,
       13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. , 17.5, 18. ,
       18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5,
       24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. ,
       29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5, 34. , 34.5,
       35. , 35.5, 36. , 36.5, 37. , 37.5, 38. , 38.5, 39. , 39.5, 40. ,
       40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5, 44. , 44.5, 45. , 45.5,
       46. , 46.5, 47. , 47.5, 48. , 48.5, 49. , 49.5, 50. , 50.5, 51. ,
       51.5, 52. , 52.5, 53. , 53.5, 54. , 54.5, 55. , 55.5, 56. , 56.5,
       57. , 57.5, 58. , 58.5, 59. , 59.5, 60. , 60.5, 61. , 61.5, 62. ,
       62.5, 63. , 63.5, 64. , 64.5, 65. , 65.5, 66. , 66.5, 67. , 67.5,
       68. , 68.5, 69. , 69.5, 70. , 70.5, 71. , 71.5, 72. , 72.5, 73. ,
       73.5, 74. , 74.5, 75. , 75.5, 76. , 76.5])

In [26]:
print(a)

[1 2 3 4]


In [27]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


In [28]:
b[0:3:2]

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [33]:
194/2

97.0

In [38]:
 m=f.reshape(97,2)
print(m)

[[ 2.   2.5]
 [ 3.   3.5]
 [ 4.   4.5]
 [ 5.   5.5]
 [ 6.   6.5]
 [ 7.   7.5]
 [ 8.   8.5]
 [ 9.   9.5]
 [10.  10.5]
 [11.  11.5]
 [12.  12.5]
 [13.  13.5]
 [14.  14.5]
 [15.  15.5]
 [16.  16.5]
 [17.  17.5]
 [18.  18.5]
 [19.  19.5]
 [20.  20.5]
 [21.  21.5]
 [22.  22.5]
 [23.  23.5]
 [24.  24.5]
 [25.  25.5]
 [26.  26.5]
 [27.  27.5]
 [28.  28.5]
 [29.  29.5]
 [30.  30.5]
 [31.  31.5]
 [32.  32.5]
 [33.  33.5]
 [34.  34.5]
 [35.  35.5]
 [36.  36.5]
 [37.  37.5]
 [38.  38.5]
 [39.  39.5]
 [40.  40.5]
 [41.  41.5]
 [42.  42.5]
 [43.  43.5]
 [44.  44.5]
 [45.  45.5]
 [46.  46.5]
 [47.  47.5]
 [48.  48.5]
 [49.  49.5]
 [50.  50.5]
 [51.  51.5]
 [52.  52.5]
 [53.  53.5]
 [54.  54.5]
 [55.  55.5]
 [56.  56.5]
 [57.  57.5]
 [58.  58.5]
 [59.  59.5]
 [60.  60.5]
 [61.  61.5]
 [62.  62.5]
 [63.  63.5]
 [64.  64.5]
 [65.  65.5]
 [66.  66.5]
 [67.  67.5]
 [68.  68.5]
 [69.  69.5]
 [70.  70.5]
 [71.  71.5]
 [72.  72.5]
 [73.  73.5]
 [74.  74.5]
 [75.  75.5]
 [76.  76.5]
 [77.  77.5]
 [78.  78.5]

m[1:72:4]

In [39]:
m[0:72:5]

array([[ 2. ,  2.5],
       [ 7. ,  7.5],
       [12. , 12.5],
       [17. , 17.5],
       [22. , 22.5],
       [27. , 27.5],
       [32. , 32.5],
       [37. , 37.5],
       [42. , 42.5],
       [47. , 47.5],
       [52. , 52.5],
       [57. , 57.5],
       [62. , 62.5],
       [67. , 67.5],
       [72. , 72.5]])

In [43]:
m[50:,1:]

array([[52.5],
       [53.5],
       [54.5],
       [55.5],
       [56.5],
       [57.5],
       [58.5],
       [59.5],
       [60.5],
       [61.5],
       [62.5],
       [63.5],
       [64.5],
       [65.5],
       [66.5],
       [67.5],
       [68.5],
       [69.5],
       [70.5],
       [71.5],
       [72.5],
       [73.5],
       [74.5],
       [75.5],
       [76.5],
       [77.5],
       [78.5],
       [79.5],
       [80.5],
       [81.5],
       [82.5],
       [83.5],
       [84.5],
       [85.5],
       [86.5],
       [87.5],
       [88.5],
       [89.5],
       [90.5],
       [91.5],
       [92.5],
       [93.5],
       [94.5],
       [95.5],
       [96.5],
       [97.5],
       [98.5]])