In [1]:
print('hello world')

hello world


In [3]:
import numpy as np

In [4]:
a=np.array((5,5))

In [10]:
a=np.full((5,5),4)
print(a)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [11]:
print('orginal array:\n',a)

orginal array:
 [[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [13]:
#slicing
temp=a[:2,:3]
print(temp)

[[4 4 4]
 [4 4 4]]


In [15]:
#integer array indexing 
k=a[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices (0,3),(1,2),(2,1),(3,0):\n",a)


Elements at indices (0,3),(1,2),(2,1),(3,0):
 [[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [18]:
#boolean array indesing 
cond=a>2
k=a[cond]
print(k)

[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]


In [23]:
#return every other element from the entire array:
arr=np.array([1,2,3,4,5,6,7])
print("\norginal array:",arr)
print("\nreturns every other elements in the array:arr[::2]:",arr[::2])


orginal array: [1 2 3 4 5 6 7]

returns every other elements in the array:arr[::2]: [1 3 5 7]


In [25]:
#joining 2 arrays 
arr1=np.array([4,5,6])
arr2=np.array([7,8,9])
m=np.concatenate((arr1,arr2))
print(m)

[4 5 6 7 8 9]


In [26]:
#horizontal joining
n=np.hstack((arr1,arr2))
print(n)

[4 5 6 7 8 9]


In [27]:
k=np.vstack((arr1,arr2))
print(k)

[[4 5 6]
 [7 8 9]]


In [30]:
#depth join 
h=np.dstack((arr1,arr2))
print(h)

[[[4 7]
  [5 8]
  [6 9]]]


In [34]:
#depth join
p=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
o=np.array([21,22,23,24,25,26,27,28,29,30,31,32,33,34,34,36,37,38,39,40])
j=np.dstack((p,o))
print(j)

[[[ 1 21]
  [ 2 22]
  [ 3 23]
  [ 4 24]
  [ 5 25]
  [ 6 26]
  [ 7 27]
  [ 8 28]
  [ 9 29]
  [10 30]
  [11 31]
  [12 32]
  [13 33]
  [14 34]
  [15 34]
  [16 36]
  [17 37]
  [18 38]
  [19 39]
  [20 40]]]


In [39]:
#splitting array 
k=np.array([1,2,3,4,5,6,7,8,9])
l=np.array_split(k,3)
print(l)
print(l[0])
print(l[1])

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3]
[4 5 6]
